import { INodePropertyOptions } from 'n8n-workflow';

/**
 * @deprecated Country values are not interchangeable between contact and company
 * filters: contact criteria take ISO-2 codes, company locations take full names.
 * Use getContactCountryOptions() or getCompanyCountryOptions() instead. Retained
 * because it is re-exported from the package entrypoint.
 */
export function getCountryOptions(): INodePropertyOptions[] {
	return getCompanyCountryOptions();
}

export function getDepartmentOptions(): INodePropertyOptions[] {
	return [
		{ name: 'Business Development', value: 'Business Development' },
		{ name: 'Consulting', value: 'Consulting' },
		{ name: 'Customer Service', value: 'Customer Service' },
		{ name: 'Engineering & Technical', value: 'Engineering & Technical' },
		{ name: 'Finance', value: 'Finance' },
		{ name: 'General Management', value: 'General Management' },
		{ name: 'Health Care & Medical', value: 'Health Care & Medical' },
		{ name: 'Human Resources', value: 'Human Resources' },
		{ name: 'Information Technology', value: 'Information Technology' },
		{ name: 'Legal', value: 'Legal' },
		{ name: 'Marketing', value: 'Marketing' },
		{ name: 'Operations', value: 'Operations' },
		{ name: 'Other', value: 'Other' },
		{ name: 'Product', value: 'Product' },
		{ name: 'Research & Analytics', value: 'Research & Analytics' },
		{ name: 'Sales', value: 'Sales' },
	];
}

/**
 * Contact seniority IDs, verified against GET /v3/contacts/prospecting/filters/seniority.
 * filters.contacts.include.seniorityIds is an array of INTEGERS — these were
 * previously strings here, which did not match what the node sends.
 */
export function getSeniorityOptions(): INodePropertyOptions[] {
	return [
		{ name: 'Founder', value: 10 },
		{ name: 'C-Suite', value: 9 },
		{ name: 'Vice President', value: 8 },
		{ name: 'Partner', value: 7 },
		{ name: 'Director', value: 6 },
		{ name: 'Manager', value: 5 },
		{ name: 'Senior', value: 4 },
		{ name: 'Entry', value: 3 },
		{ name: 'Intern', value: 2 },
		{ name: 'Other', value: 1 },
	];
}

/**
 * Company main-industry IDs, generated from GET /v3/companies/prospecting/filters/industriesLabels.
 * Regenerate rather than hand-edit: these IDs drift, and an unknown ID is accepted
 * by the API with HTTP 200 and total=0 instead of an error, so a stale entry looks
 * like "no matches" rather than a bug.
 */
export function getMainIndustryOptions(): INodePropertyOptions[] {
	return [
		{ name: 'Hospitality', value: '1' },
		{ name: 'Construction', value: '3' },
		{ name: 'Community & Nonprofit Organizations', value: '5' },
		{ name: 'Education', value: '6' },
		{ name: 'Entertainment', value: '7' },
		{ name: 'Farming, Ranching, Forestry', value: '8' },
		{ name: 'Finance', value: '9' },
		{ name: 'Government', value: '10' },
		{ name: 'Healthcare', value: '11' },
		{ name: 'Manufacturing', value: '12' },
		{ name: 'Oil, Gas & Mining', value: '13' },
		{ name: 'Business Services', value: '14' },
		{ name: 'Real Estate', value: '15' },
		{ name: 'Retail & Wholesale Trade', value: '16' },
		{ name: 'Technology, Information & Media', value: '17' },
		{ name: 'Transportation & Logistics', value: '18' },
		{ name: 'Utilities', value: '19' },
	];
}

/**
 * Company sub-industry IDs from the same catalog, grouped by parent industry.
 * Labels that occur under more than one parent (e.g. "Other") are parent-qualified
 * so the dropdown stays unambiguous.
 */
export function getSubIndustryOptions(): INodePropertyOptions[] {
	return [
		// Hospitality
		{ name: 'Food & Beverage Services', value: '1' },
		{ name: 'Restaurants', value: '2' },
		{ name: 'Hotels & Accommodation Services', value: '3' },
		{ name: 'Events Services', value: '5' },
		{ name: 'Travel & Reservation Services', value: '11' },
		{ name: 'Hospitality: Other', value: '778' },
		// Construction
		{ name: 'Specialty Trade Contractors', value: '13' },
		{ name: 'Building Construction', value: '15' },
		{ name: 'Civil Engineering', value: '16' },
		{ name: 'Construction: Other', value: '791' },
		// Community & Nonprofit Organizations
		{ name: 'Fundraising', value: '7' },
		{ name: 'Philanthropic Fundraising Services', value: '18' },
		{ name: 'Political Organizations', value: '20' },
		{ name: 'Civic & Social Organizations', value: '21' },
		{ name: 'Religious Institutions', value: '22' },
		{ name: 'Community & Nonprofit Organizations: Other', value: '793' },
		// Education
		{ name: 'E-Learning Providers', value: '23' },
		{ name: 'Higher Education', value: '24' },
		{ name: 'Primary & Secondary Education', value: '25' },
		{ name: 'Training', value: '26' },
		{ name: 'Preschools & Kindergartens', value: '27' },
		{ name: 'Education Administration Programs', value: '50' },
		{ name: 'Extracurricular & Enrichment Education', value: '140' },
		{ name: 'Education: Other', value: '794' },
		// Entertainment
		{ name: 'Entertainment Providers', value: '28' },
		{ name: 'Museums, Historical Sites, & Zoos', value: '29' },
		{ name: 'Arts & Cultural Creators', value: '30' },
		{ name: 'Performing Arts', value: '31' },
		{ name: 'Sports', value: '32' },
		{ name: 'Recreational Facilities', value: '33' },
		{ name: 'Gambling Facilities & Casinos', value: '34' },
		{ name: 'Wellness & Fitness Services', value: '35' },
		{ name: 'Entertainment: Other', value: '795' },
		// Farming, Ranching, Forestry
		{ name: 'Farming, Ranching, Forestry', value: '36' },
		// Finance
		{ name: 'Financial Services', value: '37' },
		{ name: 'Capital Markets', value: '38' },
		{ name: 'Investment', value: '40' },
		{ name: 'Venture Capital & Private Equity Principals', value: '41' },
		{ name: 'Banking', value: '42' },
		{ name: 'International Trade & Development', value: '43' },
		{ name: 'Insurance', value: '44' },
		{ name: 'Accounting & Services', value: '92' },
		{ name: 'Finance: Other', value: '797' },
		// Government
		{ name: 'Government Administration', value: '45' },
		{ name: 'Administration of Justice', value: '46' },
		{ name: 'Public Safety', value: '49' },
		{ name: 'Housing & Community Development', value: '52' },
		{ name: 'Government Executive Offices', value: '56' },
		{ name: 'Government: Other', value: '779' },
		// Healthcare
		{ name: 'Hospitals & Clinics', value: '59' },
		{ name: 'Community & Home Healthcare Services', value: '60' },
		{ name: 'Alternative Medicine', value: '62' },
		{ name: 'Mental Health Care', value: '64' },
		{ name: 'Medical Practices', value: '65' },
		{ name: 'Nursing Homes & Residential Care Facilities', value: '66' },
		{ name: 'Biotechnology Research Services', value: '106' },
		{ name: 'Veterinary Services', value: '108' },
		{ name: 'Healthcare: Other', value: '780' },
		// Manufacturing
		{ name: 'Computer & Electronics Manufacturing', value: '68' },
		{ name: 'Chemicals & Related Products', value: '69' },
		{ name: 'Personal Care Products', value: '70' },
		{ name: 'Pharmaceuticals Manufacturing', value: '71' },
		{ name: 'Semiconductor & Renewable Energy Semiconductor', value: '74' },
		{ name: 'Fabricated Metal Products', value: '75' },
		{ name: 'Food & Beverage', value: '76' },
		{ name: 'Furniture', value: '77' },
		{ name: 'Glass, Ceramics, Clay & Concrete', value: '78' },
		{ name: 'Industrial Machinery & Equipment', value: '79' },
		{ name: 'Medical Equipment', value: '80' },
		{ name: 'Paper & Forest Product', value: '81' },
		{ name: 'Plastics & Rubber Products', value: '82' },
		{ name: 'Sporting Goods Manufacturing', value: '83' },
		{ name: 'Textile & Apparel Manufacturing', value: '84' },
		{ name: 'Aerospace & Defense', value: '86' },
		{ name: 'Motor Vehicles', value: '87' },
		{ name: 'Transportation Equipment & Machinery', value: '89' },
		{ name: 'Manufacturing: Other', value: '781' },
		// Oil, Gas & Mining
		{ name: 'Mining', value: '90' },
		{ name: 'Oil & Gas', value: '91' },
		{ name: 'Oil, Gas & Mining: Other', value: '782' },
		// Business Services
		{ name: 'Security & Investigations', value: '8' },
		{ name: 'Staffing & Recruiting', value: '9' },
		{ name: 'Translation & Localization', value: '10' },
		{ name: 'Writing & Editing', value: '12' },
		{ name: 'Advertising, Public Relations & Marketing Services', value: '93' },
		{ name: 'Architecture & Planning', value: '96' },
		{ name: 'Business Consulting & Services', value: '97' },
		{ name: 'Environmental Services', value: '98' },
		{ name: 'Human Resources Services', value: '99' },
		{ name: 'Outsourcing & Offshoring Consulting', value: '100' },
		{ name: 'Design Services', value: '101' },
		{ name: 'Law Firms & Legal Services', value: '104' },
		{ name: 'Photography Services', value: '105' },
		{ name: 'Business Services: Other', value: '783' },
		// Real Estate
		{ name: 'Facilities Services', value: '6' },
		{ name: 'Property Management', value: '142' },
		{ name: 'Real Estate Agencies', value: '143' },
		{ name: 'Real Estate Investment and Development', value: '144' },
		{ name: 'Real Estate: Other', value: '796' },
		// Retail & Wholesale Trade
		{ name: 'Luxury Goods & Jewelry Retail', value: '110' },
		{ name: 'Food & Beverage Retail', value: '111' },
		{ name: 'Apparel & Fashion Retail', value: '113' },
		{ name: 'Home & Office Equipment Retail', value: '114' },
		{ name: 'General Merchandise Retail', value: '115' },
		{ name: 'Building & Garden Materials', value: '138' },
		{ name: 'Wholesale Import & Export', value: '139' },
		{ name: 'Health & Personal Care Stores Retail', value: '145' },
		{ name: 'Motor Vehicle, Parts Dealers & Tire Stores', value: '146' },
		{ name: 'Sport, Music, Books & Hobbies Retail', value: '147' },
		{ name: 'Retail & Wholesale Trade: Other', value: '785' },
		// Technology, Information & Media
		{ name: 'IT Consulting & IT Services', value: '103' },
		{ name: 'Book & Newspaper Publishing', value: '116' },
		{ name: 'Broadcast Media Production & Distribution', value: '117' },
		{ name: 'Movies, Videos & Sound', value: '118' },
		{ name: 'Telecommunications', value: '119' },
		{ name: 'Digital Information & Data Solutions', value: '120' },
		{ name: 'Information Services', value: '122' },
		{ name: 'Internet Publishing', value: '123' },
		{ name: 'E-Commerce & Marketplace', value: '124' },
		{ name: 'Computer & Mobile Games', value: '126' },
		{ name: 'Computer & Network Security Services', value: '128' },
		{ name: 'Software Development', value: '129' },
		{ name: 'Computer Systems Architectural, Design & Services', value: '148' },
		{ name: 'Technology, Information & Media: Other', value: '786' },
		// Transportation & Logistics
		{ name: 'Airlines, Airports & Air Services', value: '130' },
		{ name: 'Freight & Package Transportation', value: '131' },
		{ name: 'Ground Passenger Transportation', value: '132' },
		{ name: 'Maritime Transportation', value: '133' },
		{ name: 'Truck Transportation', value: '134' },
		{ name: 'Warehousing & Storage', value: '135' },
		{ name: 'Transportation & Logistics: Other', value: '787' },
		// Utilities
		{ name: 'Utilities', value: '136' },
	];
}

/**
 * Contact-level country filter values. filters.contacts.include.countries accepts
 * ISO-2 codes ONLY — a full country name is rejected with "must be shorter than or
 * equal to 2 characters". Generated from GET /v3/contacts/prospecting/filters/countries.
 */
export function getContactCountryOptions(): INodePropertyOptions[] {
	return [
		{ name: 'United States', value: 'US' },
		{ name: 'India', value: 'IN' },
		{ name: 'United Kingdom', value: 'GB' },
		{ name: 'Brazil', value: 'BR' },
		{ name: 'Canada', value: 'CA' },
		{ name: 'Australia', value: 'AU' },
		{ name: 'France', value: 'FR' },
		{ name: 'Germany', value: 'DE' },
		{ name: 'Netherlands', value: 'NL' },
		{ name: 'Italy', value: 'IT' },
		{ name: 'South Africa', value: 'ZA' },
		{ name: 'Mexico', value: 'MX' },
		{ name: 'Turkey', value: 'TR' },
		{ name: 'Sweden', value: 'SE' },
		{ name: 'China', value: 'CN' },
		{ name: 'Indonesia', value: 'ID' },
		{ name: 'Belgium', value: 'BE' },
		{ name: 'Spain', value: 'ES' },
		{ name: 'United Arab Emirates', value: 'AE' },
		{ name: 'Argentina', value: 'AR' },
		{ name: 'Switzerland', value: 'CH' },
		{ name: 'Singapore', value: 'SG' },
		{ name: 'Saudi Arabia', value: 'SA' },
		{ name: 'Ireland', value: 'IE' },
		{ name: 'Colombia', value: 'CO' },
		{ name: 'Chile', value: 'CL' },
		{ name: 'Malaysia', value: 'MY' },
		{ name: 'Egypt', value: 'EG' },
		{ name: 'Nigeria', value: 'NG' },
		{ name: 'Japan', value: 'JP' },
		{ name: 'Hong Kong', value: 'HK' },
		{ name: 'Finland', value: 'FI' },
		{ name: 'Denmark', value: 'DK' },
		{ name: 'Taiwan, Province Of China', value: 'TW' },
		{ name: 'Bangladesh', value: 'BD' },
		{ name: 'Austria', value: 'AT' },
		{ name: 'Czech Republic', value: 'CZ' },
		{ name: 'Peru', value: 'PE' },
		{ name: 'Kenya', value: 'KE' },
		{ name: 'Vietnam', value: 'VN' },
		{ name: 'Poland', value: 'PL' },
		{ name: 'Ukraine', value: 'UA' },
		{ name: 'Thailand', value: 'TH' },
		{ name: 'South Korea', value: 'KR' },
		{ name: 'Iran', value: 'IR' },
		{ name: 'Morocco', value: 'MA' },
		{ name: 'Venezuela', value: 'VE' },
		{ name: 'Hungary', value: 'HU' },
		{ name: 'Sri Lanka', value: 'LK' },
		{ name: 'New Zealand', value: 'NZ' },
		{ name: 'Portugal', value: 'PT' },
		{ name: 'Greece', value: 'GR' },
		{ name: 'Romania', value: 'RO' },
		{ name: 'Ecuador', value: 'EC' },
		{ name: 'Norway', value: 'NO' },
		{ name: 'Russia', value: 'RU' },
		{ name: 'Bulgaria', value: 'BG' },
		{ name: 'Philippines', value: 'PH' },
		{ name: 'Costa Rica', value: 'CR' },
		{ name: 'Slovakia', value: 'SK' },
		{ name: 'Ghana', value: 'GH' },
		{ name: 'Puerto Rico', value: 'PR' },
		{ name: 'Croatia', value: 'HR' },
		{ name: 'Tunisia', value: 'TN' },
		{ name: 'Jordan', value: 'JO' },
		{ name: 'Algeria', value: 'DZ' },
		{ name: 'Lebanon', value: 'LB' },
		{ name: 'Panama', value: 'PA' },
		{ name: 'Uruguay', value: 'UY' },
		{ name: 'Lithuania', value: 'LT' },
		{ name: 'Kuwait', value: 'KW' },
		{ name: 'Pakistan', value: 'PK' },
		{ name: 'Dominican Republic', value: 'DO' },
		{ name: 'Luxembourg', value: 'LU' },
		{ name: 'Azerbaijan', value: 'AZ' },
		{ name: 'Guatemala', value: 'GT' },
		{ name: 'Uganda', value: 'UG' },
		{ name: 'Oman', value: 'OM' },
		{ name: 'Georgia', value: 'GE' },
		{ name: 'Slovenia', value: 'SI' },
		{ name: 'Jamaica', value: 'JM' },
		{ name: 'Nepal', value: 'NP' },
		{ name: 'Tanzania, United Republic Of', value: 'TZ' },
		{ name: 'Belarus', value: 'BY' },
		{ name: 'Kazakhstan', value: 'KZ' },
		{ name: 'Zimbabwe', value: 'ZW' },
		{ name: 'Trinidad And Tobago', value: 'TT' },
		{ name: 'Zambia', value: 'ZM' },
		{ name: 'Ethiopia', value: 'ET' },
		{ name: 'Estonia', value: 'EE' },
		{ name: 'Latvia', value: 'LV' },
		{ name: 'Angola', value: 'AO' },
		{ name: 'Bahrain', value: 'BH' },
		{ name: 'Cote D\'Ivoire', value: 'CI' },
		{ name: 'Bolivia', value: 'BO' },
		{ name: 'Senegal', value: 'SN' },
		{ name: 'Albania', value: 'AL' },
		{ name: 'Iraq', value: 'IQ' },
		{ name: 'El Salvador', value: 'SV' },
		{ name: 'Qatar', value: 'QA' },
		{ name: 'Cyprus', value: 'CY' },
		{ name: 'Cambodia', value: 'KH' },
		{ name: 'Malta', value: 'MT' },
		{ name: 'Mauritius', value: 'MU' },
		{ name: 'Mozambique', value: 'MZ' },
		{ name: 'Macedonia', value: 'MK' },
		{ name: 'Congo', value: 'CG' },
		{ name: 'Armenia', value: 'AM' },
		{ name: 'Honduras', value: 'HN' },
		{ name: 'Papua New Guinea', value: 'PG' },
		{ name: 'Serbia', value: 'RS' },
		{ name: 'Bosnia And Herzegovina', value: 'BA' },
		{ name: 'Paraguay', value: 'PY' },
		{ name: 'Botswana', value: 'BW' },
		{ name: 'Cameroon', value: 'CM' },
		{ name: 'Myanmar', value: 'MM' },
		{ name: 'Afghanistan', value: 'AF' },
		{ name: 'Namibia', value: 'NA' },
		{ name: 'Moldova', value: 'MD' },
		{ name: 'Nicaragua', value: 'NI' },
		{ name: 'Palestine', value: 'PS' },
		{ name: 'Macao', value: 'MO' },
		{ name: 'Fiji', value: 'FJ' },
		{ name: 'Rwanda', value: 'RW' },
		{ name: 'Malawi', value: 'MW' },
		{ name: 'Mongolia', value: 'MN' },
		{ name: 'Bahamas', value: 'BS' },
		{ name: 'Jersey', value: 'JE' },
		{ name: 'Madagascar', value: 'MG' },
		{ name: 'Gabon', value: 'GA' },
		{ name: 'Reunion', value: 'RE' },
		{ name: 'Sudan', value: 'SD' },
		{ name: 'New Caledonia', value: 'NC' },
		{ name: 'Uzbekistan', value: 'UZ' },
		{ name: 'Maldives', value: 'MV' },
		{ name: 'Mali', value: 'ML' },
		{ name: 'Barbados', value: 'BB' },
		{ name: 'Grenada', value: 'GD' },
		{ name: 'Burkina Faso', value: 'BF' },
		{ name: 'Syrian Arab Republic', value: 'SY' },
		{ name: 'Iceland', value: 'IS' },
		{ name: 'Cayman Islands', value: 'KY' },
		{ name: 'Benin', value: 'BJ' },
		{ name: 'Montenegro', value: 'ME' },
		{ name: 'Haiti', value: 'HT' },
		{ name: 'Bermuda', value: 'BM' },
		{ name: 'Monaco', value: 'MC' },
		{ name: 'Libya', value: 'LY' },
		{ name: 'Guadeloupe', value: 'GP' },
		{ name: 'Brunei Darussalam', value: 'BN' },
		{ name: 'Isle Of Man', value: 'IM' },
		{ name: 'Guernsey', value: 'GG' },
		{ name: 'Curacao', value: 'CW' },
		{ name: 'Somalia', value: 'SO' },
		{ name: 'Guinea', value: 'GN' },
		{ name: 'Guam', value: 'GU' },
		{ name: 'Suriname', value: 'SR' },
		{ name: 'Yemen', value: 'YE' },
		{ name: 'Martinique', value: 'MQ' },
		{ name: 'Guyana', value: 'GY' },
		{ name: 'Swaziland', value: 'SZ' },
		{ name: 'Liberia', value: 'LR' },
		{ name: 'Sierra Leone', value: 'SL' },
		{ name: 'Gibraltar', value: 'GI' },
		{ name: 'Vatican City', value: 'VA' },
		{ name: 'Cuba', value: 'CU' },
		{ name: 'Lesotho', value: 'LS' },
		{ name: 'Kyrgyzstan', value: 'KG' },
		{ name: 'Niger', value: 'NE' },
		{ name: 'Aruba', value: 'AW' },
		{ name: 'American Virgin Islands', value: 'VI' },
		{ name: 'Seychelles', value: 'SC' },
		{ name: 'Andorra', value: 'AD' },
		{ name: 'Saint Lucia', value: 'LC' },
		{ name: 'Belize', value: 'BZ' },
		{ name: 'Gambia', value: 'GM' },
		{ name: 'Mauritania', value: 'MR' },
		{ name: 'South Sudan', value: 'SS' },
		{ name: 'Liechtenstein', value: 'LI' },
		{ name: 'Montserrat', value: 'MS' },
		{ name: 'Chad', value: 'TD' },
		{ name: 'Bhutan', value: 'BT' },
		{ name: 'French Polynesia', value: 'PF' },
		{ name: 'Cape Verde', value: 'CV' },
		{ name: 'Burundi', value: 'BI' },
		{ name: 'French Guiana', value: 'GF' },
		{ name: 'Tajikistan', value: 'TJ' },
		{ name: 'Turkmenistan', value: 'TM' },
		{ name: 'Antigua And Barbuda', value: 'AG' },
		{ name: 'Djibouti', value: 'DJ' },
		{ name: 'British Virgin Islands', value: 'VG' },
		{ name: 'Lao People\'S Democratic Republic', value: 'LA' },
		{ name: 'American Samoa', value: 'AS' },
		{ name: 'Central African Republic', value: 'CF' },
		{ name: 'Timor-Leste', value: 'TL' },
		{ name: 'Equatorial Guinea', value: 'GQ' },
		{ name: 'Dominica', value: 'DM' },
		{ name: 'Togo', value: 'TG' },
		{ name: 'Bonaire', value: 'BQ' },
		{ name: 'San Marino', value: 'SM' },
		{ name: 'Saint Barthelemy', value: 'BL' },
		{ name: 'Niue', value: 'NU' },
		{ name: 'Israel', value: 'IL' },
		{ name: 'Anguilla', value: 'AI' },
		{ name: 'Vanuatu', value: 'VU' },
		{ name: 'Saint Vincent And The Grenadines', value: 'VC' },
		{ name: 'Tonga', value: 'TO' },
		{ name: 'Faroe Islands', value: 'FO' },
		{ name: 'Greenland', value: 'GL' },
		{ name: 'Christmas Island', value: 'CX' },
		{ name: 'Western Sahara', value: 'EH' },
		{ name: 'Solomon Islands', value: 'SB' },
		{ name: 'Samoa', value: 'WS' },
		{ name: 'Eritrea', value: 'ER' },
		{ name: 'Saint Kitts And Nevis', value: 'KN' },
		{ name: 'Falkland Islands', value: 'FK' },
		{ name: 'Northern Mariana Islands', value: 'MP' },
		{ name: 'Antarctica', value: 'AQ' },
		{ name: 'Mayotte', value: 'YT' },
		{ name: 'Cook Islands', value: 'CK' },
		{ name: 'Democratic Republic Of The Congo', value: 'CD' },
		{ name: 'Sao Tome And Principe', value: 'ST' },
		{ name: 'Marshall Islands', value: 'MH' },
		{ name: 'North Korea', value: 'KP' },
		{ name: 'Comoros', value: 'KM' },
		{ name: 'Palau', value: 'PW' },
		{ name: 'Turks And Caicos Islands', value: 'TC' },
		{ name: 'British Indian Ocean', value: 'IO' },
		{ name: 'Micronesia', value: 'FM' },
		{ name: 'Sint Maarten (Dutch Part)', value: 'SX' },
		{ name: 'Netherlands Antilles', value: 'AN' },
		{ name: 'Norfolk Island', value: 'NF' },
		{ name: 'Saint Helena, Ascension And Tristan Da Cunha', value: 'SH' },
		{ name: 'Wallis And Futuna', value: 'WF' },
		{ name: 'Nauru', value: 'NR' },
		{ name: 'Kiribati', value: 'KI' },
		{ name: 'Tuvalu', value: 'TV' },
		{ name: 'Aland Islands', value: 'AX' },
		{ name: 'Svalbard And Jan Mayen', value: 'SJ' },
		{ name: 'Tokelau', value: 'TK' },
		{ name: 'French Southern Territories', value: 'TF' },
		{ name: 'Saint Pierre And Miquelon', value: 'PM' },
		{ name: 'Pitcairn', value: 'PN' },
		{ name: 'Guinea-Bissau', value: 'GW' },
	];
}

/**
 * Company-level location country values. V3Location.country expects the FULL country
 * name; there is no countryIso2 on company criteria (companies prospecting rejects it
 * outright, and contacts prospecting accepts it but then matches nothing).
 */
export function getCompanyCountryOptions(): INodePropertyOptions[] {
	return [
		{ name: 'United States', value: 'United States' },
		{ name: 'India', value: 'India' },
		{ name: 'United Kingdom', value: 'United Kingdom' },
		{ name: 'Brazil', value: 'Brazil' },
		{ name: 'Canada', value: 'Canada' },
		{ name: 'Australia', value: 'Australia' },
		{ name: 'France', value: 'France' },
		{ name: 'Germany', value: 'Germany' },
		{ name: 'Netherlands', value: 'Netherlands' },
		{ name: 'Italy', value: 'Italy' },
		{ name: 'South Africa', value: 'South Africa' },
		{ name: 'Mexico', value: 'Mexico' },
		{ name: 'Turkey', value: 'Turkey' },
		{ name: 'Sweden', value: 'Sweden' },
		{ name: 'China', value: 'China' },
		{ name: 'Indonesia', value: 'Indonesia' },
		{ name: 'Belgium', value: 'Belgium' },
		{ name: 'Spain', value: 'Spain' },
		{ name: 'United Arab Emirates', value: 'United Arab Emirates' },
		{ name: 'Argentina', value: 'Argentina' },
		{ name: 'Switzerland', value: 'Switzerland' },
		{ name: 'Singapore', value: 'Singapore' },
		{ name: 'Saudi Arabia', value: 'Saudi Arabia' },
		{ name: 'Ireland', value: 'Ireland' },
		{ name: 'Colombia', value: 'Colombia' },
		{ name: 'Chile', value: 'Chile' },
		{ name: 'Malaysia', value: 'Malaysia' },
		{ name: 'Egypt', value: 'Egypt' },
		{ name: 'Nigeria', value: 'Nigeria' },
		{ name: 'Japan', value: 'Japan' },
		{ name: 'Hong Kong', value: 'Hong Kong' },
		{ name: 'Finland', value: 'Finland' },
		{ name: 'Denmark', value: 'Denmark' },
		{ name: 'Taiwan, Province Of China', value: 'Taiwan, Province Of China' },
		{ name: 'Bangladesh', value: 'Bangladesh' },
		{ name: 'Austria', value: 'Austria' },
		{ name: 'Czech Republic', value: 'Czech Republic' },
		{ name: 'Peru', value: 'Peru' },
		{ name: 'Kenya', value: 'Kenya' },
		{ name: 'Vietnam', value: 'Vietnam' },
		{ name: 'Poland', value: 'Poland' },
		{ name: 'Ukraine', value: 'Ukraine' },
		{ name: 'Thailand', value: 'Thailand' },
		{ name: 'South Korea', value: 'South Korea' },
		{ name: 'Iran', value: 'Iran' },
		{ name: 'Morocco', value: 'Morocco' },
		{ name: 'Venezuela', value: 'Venezuela' },
		{ name: 'Hungary', value: 'Hungary' },
		{ name: 'Sri Lanka', value: 'Sri Lanka' },
		{ name: 'New Zealand', value: 'New Zealand' },
		{ name: 'Portugal', value: 'Portugal' },
		{ name: 'Greece', value: 'Greece' },
		{ name: 'Romania', value: 'Romania' },
		{ name: 'Ecuador', value: 'Ecuador' },
		{ name: 'Norway', value: 'Norway' },
		{ name: 'Russia', value: 'Russia' },
		{ name: 'Bulgaria', value: 'Bulgaria' },
		{ name: 'Philippines', value: 'Philippines' },
		{ name: 'Costa Rica', value: 'Costa Rica' },
		{ name: 'Slovakia', value: 'Slovakia' },
		{ name: 'Ghana', value: 'Ghana' },
		{ name: 'Puerto Rico', value: 'Puerto Rico' },
		{ name: 'Croatia', value: 'Croatia' },
		{ name: 'Tunisia', value: 'Tunisia' },
		{ name: 'Jordan', value: 'Jordan' },
		{ name: 'Algeria', value: 'Algeria' },
		{ name: 'Lebanon', value: 'Lebanon' },
		{ name: 'Panama', value: 'Panama' },
		{ name: 'Uruguay', value: 'Uruguay' },
		{ name: 'Lithuania', value: 'Lithuania' },
		{ name: 'Kuwait', value: 'Kuwait' },
		{ name: 'Pakistan', value: 'Pakistan' },
		{ name: 'Dominican Republic', value: 'Dominican Republic' },
		{ name: 'Luxembourg', value: 'Luxembourg' },
		{ name: 'Azerbaijan', value: 'Azerbaijan' },
		{ name: 'Guatemala', value: 'Guatemala' },
		{ name: 'Uganda', value: 'Uganda' },
		{ name: 'Oman', value: 'Oman' },
		{ name: 'Georgia', value: 'Georgia' },
		{ name: 'Slovenia', value: 'Slovenia' },
		{ name: 'Jamaica', value: 'Jamaica' },
		{ name: 'Nepal', value: 'Nepal' },
		{ name: 'Tanzania, United Republic Of', value: 'Tanzania, United Republic Of' },
		{ name: 'Belarus', value: 'Belarus' },
		{ name: 'Kazakhstan', value: 'Kazakhstan' },
		{ name: 'Zimbabwe', value: 'Zimbabwe' },
		{ name: 'Trinidad And Tobago', value: 'Trinidad And Tobago' },
		{ name: 'Zambia', value: 'Zambia' },
		{ name: 'Ethiopia', value: 'Ethiopia' },
		{ name: 'Estonia', value: 'Estonia' },
		{ name: 'Latvia', value: 'Latvia' },
		{ name: 'Angola', value: 'Angola' },
		{ name: 'Bahrain', value: 'Bahrain' },
		{ name: 'Cote D\'Ivoire', value: 'Cote D\'Ivoire' },
		{ name: 'Bolivia', value: 'Bolivia' },
		{ name: 'Senegal', value: 'Senegal' },
		{ name: 'Albania', value: 'Albania' },
		{ name: 'Iraq', value: 'Iraq' },
		{ name: 'El Salvador', value: 'El Salvador' },
		{ name: 'Qatar', value: 'Qatar' },
		{ name: 'Cyprus', value: 'Cyprus' },
		{ name: 'Cambodia', value: 'Cambodia' },
		{ name: 'Malta', value: 'Malta' },
		{ name: 'Mauritius', value: 'Mauritius' },
		{ name: 'Mozambique', value: 'Mozambique' },
		{ name: 'Macedonia', value: 'Macedonia' },
		{ name: 'Congo', value: 'Congo' },
		{ name: 'Armenia', value: 'Armenia' },
		{ name: 'Honduras', value: 'Honduras' },
		{ name: 'Papua New Guinea', value: 'Papua New Guinea' },
		{ name: 'Serbia', value: 'Serbia' },
		{ name: 'Bosnia And Herzegovina', value: 'Bosnia And Herzegovina' },
		{ name: 'Paraguay', value: 'Paraguay' },
		{ name: 'Botswana', value: 'Botswana' },
		{ name: 'Cameroon', value: 'Cameroon' },
		{ name: 'Myanmar', value: 'Myanmar' },
		{ name: 'Afghanistan', value: 'Afghanistan' },
		{ name: 'Namibia', value: 'Namibia' },
		{ name: 'Moldova', value: 'Moldova' },
		{ name: 'Nicaragua', value: 'Nicaragua' },
		{ name: 'Palestine', value: 'Palestine' },
		{ name: 'Macao', value: 'Macao' },
		{ name: 'Fiji', value: 'Fiji' },
		{ name: 'Rwanda', value: 'Rwanda' },
		{ name: 'Malawi', value: 'Malawi' },
		{ name: 'Mongolia', value: 'Mongolia' },
		{ name: 'Bahamas', value: 'Bahamas' },
		{ name: 'Jersey', value: 'Jersey' },
		{ name: 'Madagascar', value: 'Madagascar' },
		{ name: 'Gabon', value: 'Gabon' },
		{ name: 'Reunion', value: 'Reunion' },
		{ name: 'Sudan', value: 'Sudan' },
		{ name: 'New Caledonia', value: 'New Caledonia' },
		{ name: 'Uzbekistan', value: 'Uzbekistan' },
		{ name: 'Maldives', value: 'Maldives' },
		{ name: 'Mali', value: 'Mali' },
		{ name: 'Barbados', value: 'Barbados' },
		{ name: 'Grenada', value: 'Grenada' },
		{ name: 'Burkina Faso', value: 'Burkina Faso' },
		{ name: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
		{ name: 'Iceland', value: 'Iceland' },
		{ name: 'Cayman Islands', value: 'Cayman Islands' },
		{ name: 'Benin', value: 'Benin' },
		{ name: 'Montenegro', value: 'Montenegro' },
		{ name: 'Haiti', value: 'Haiti' },
		{ name: 'Bermuda', value: 'Bermuda' },
		{ name: 'Monaco', value: 'Monaco' },
		{ name: 'Libya', value: 'Libya' },
		{ name: 'Guadeloupe', value: 'Guadeloupe' },
		{ name: 'Brunei Darussalam', value: 'Brunei Darussalam' },
		{ name: 'Isle Of Man', value: 'Isle Of Man' },
		{ name: 'Guernsey', value: 'Guernsey' },
		{ name: 'Curacao', value: 'Curacao' },
		{ name: 'Somalia', value: 'Somalia' },
		{ name: 'Guinea', value: 'Guinea' },
		{ name: 'Guam', value: 'Guam' },
		{ name: 'Suriname', value: 'Suriname' },
		{ name: 'Yemen', value: 'Yemen' },
		{ name: 'Martinique', value: 'Martinique' },
		{ name: 'Guyana', value: 'Guyana' },
		{ name: 'Swaziland', value: 'Swaziland' },
		{ name: 'Liberia', value: 'Liberia' },
		{ name: 'Sierra Leone', value: 'Sierra Leone' },
		{ name: 'Gibraltar', value: 'Gibraltar' },
		{ name: 'Vatican City', value: 'Vatican City' },
		{ name: 'Cuba', value: 'Cuba' },
		{ name: 'Lesotho', value: 'Lesotho' },
		{ name: 'Kyrgyzstan', value: 'Kyrgyzstan' },
		{ name: 'Niger', value: 'Niger' },
		{ name: 'Aruba', value: 'Aruba' },
		{ name: 'American Virgin Islands', value: 'American Virgin Islands' },
		{ name: 'Seychelles', value: 'Seychelles' },
		{ name: 'Andorra', value: 'Andorra' },
		{ name: 'Saint Lucia', value: 'Saint Lucia' },
		{ name: 'Belize', value: 'Belize' },
		{ name: 'Gambia', value: 'Gambia' },
		{ name: 'Mauritania', value: 'Mauritania' },
		{ name: 'South Sudan', value: 'South Sudan' },
		{ name: 'Liechtenstein', value: 'Liechtenstein' },
		{ name: 'Montserrat', value: 'Montserrat' },
		{ name: 'Chad', value: 'Chad' },
		{ name: 'Bhutan', value: 'Bhutan' },
		{ name: 'French Polynesia', value: 'French Polynesia' },
		{ name: 'Cape Verde', value: 'Cape Verde' },
		{ name: 'Burundi', value: 'Burundi' },
		{ name: 'French Guiana', value: 'French Guiana' },
		{ name: 'Tajikistan', value: 'Tajikistan' },
		{ name: 'Turkmenistan', value: 'Turkmenistan' },
		{ name: 'Antigua And Barbuda', value: 'Antigua And Barbuda' },
		{ name: 'Djibouti', value: 'Djibouti' },
		{ name: 'British Virgin Islands', value: 'British Virgin Islands' },
		{ name: 'Lao People\'S Democratic Republic', value: 'Lao People\'S Democratic Republic' },
		{ name: 'American Samoa', value: 'American Samoa' },
		{ name: 'Central African Republic', value: 'Central African Republic' },
		{ name: 'Timor-Leste', value: 'Timor-Leste' },
		{ name: 'Equatorial Guinea', value: 'Equatorial Guinea' },
		{ name: 'Dominica', value: 'Dominica' },
		{ name: 'Togo', value: 'Togo' },
		{ name: 'Bonaire', value: 'Bonaire' },
		{ name: 'San Marino', value: 'San Marino' },
		{ name: 'Saint Barthelemy', value: 'Saint Barthelemy' },
		{ name: 'Niue', value: 'Niue' },
		{ name: 'Israel', value: 'Israel' },
		{ name: 'Anguilla', value: 'Anguilla' },
		{ name: 'Vanuatu', value: 'Vanuatu' },
		{ name: 'Saint Vincent And The Grenadines', value: 'Saint Vincent And The Grenadines' },
		{ name: 'Tonga', value: 'Tonga' },
		{ name: 'Faroe Islands', value: 'Faroe Islands' },
		{ name: 'Greenland', value: 'Greenland' },
		{ name: 'Christmas Island', value: 'Christmas Island' },
		{ name: 'Western Sahara', value: 'Western Sahara' },
		{ name: 'Solomon Islands', value: 'Solomon Islands' },
		{ name: 'Samoa', value: 'Samoa' },
		{ name: 'Eritrea', value: 'Eritrea' },
		{ name: 'Saint Kitts And Nevis', value: 'Saint Kitts And Nevis' },
		{ name: 'Falkland Islands', value: 'Falkland Islands' },
		{ name: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
		{ name: 'Antarctica', value: 'Antarctica' },
		{ name: 'Mayotte', value: 'Mayotte' },
		{ name: 'Cook Islands', value: 'Cook Islands' },
		{ name: 'Democratic Republic Of The Congo', value: 'Democratic Republic Of The Congo' },
		{ name: 'Sao Tome And Principe', value: 'Sao Tome And Principe' },
		{ name: 'Marshall Islands', value: 'Marshall Islands' },
		{ name: 'North Korea', value: 'North Korea' },
		{ name: 'Comoros', value: 'Comoros' },
		{ name: 'Palau', value: 'Palau' },
		{ name: 'Turks And Caicos Islands', value: 'Turks And Caicos Islands' },
		{ name: 'British Indian Ocean', value: 'British Indian Ocean' },
		{ name: 'Micronesia', value: 'Micronesia' },
		{ name: 'Sint Maarten (Dutch Part)', value: 'Sint Maarten (Dutch Part)' },
		{ name: 'Netherlands Antilles', value: 'Netherlands Antilles' },
		{ name: 'Norfolk Island', value: 'Norfolk Island' },
		{ name: 'Saint Helena, Ascension And Tristan Da Cunha', value: 'Saint Helena, Ascension And Tristan Da Cunha' },
		{ name: 'Wallis And Futuna', value: 'Wallis And Futuna' },
		{ name: 'Nauru', value: 'Nauru' },
		{ name: 'Kiribati', value: 'Kiribati' },
		{ name: 'Tuvalu', value: 'Tuvalu' },
		{ name: 'Aland Islands', value: 'Aland Islands' },
		{ name: 'Svalbard And Jan Mayen', value: 'Svalbard And Jan Mayen' },
		{ name: 'Tokelau', value: 'Tokelau' },
		{ name: 'French Southern Territories', value: 'French Southern Territories' },
		{ name: 'Saint Pierre And Miquelon', value: 'Saint Pierre And Miquelon' },
		{ name: 'Pitcairn', value: 'Pitcairn' },
		{ name: 'Guinea-Bissau', value: 'Guinea-Bissau' },
	];
}
